name: "Feature Request"
description: Feature request
title: "[Feature]: "
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |+
        ## WordLLMs Feature Request

        Please submit according to this template, otherwise it will be closed.
        **Before asking, please check the README and closed issues. Duplicate questions will be closed.**

  - type: checkboxes
    id: read
    attributes:
      label: Pre-reading
      description: I have searched and read the following (please tick after reading)
      options:
        - label: "[Issues](https://github.com/kauttoj/WordLLMs/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)"
          required: true
        - label: "[README](https://github.com/kauttoj/WordLLMs/blob/master/README.md)"
          required: true
  - type: dropdown
    id: service
    attributes:
      label: Service Type
      options:
        - Official hosted service
        - Self-hosted service
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: System Information
      options:
        - Windows
        - Mac
        - Mac(arm64)
        - Linux
        - All
    validations:
      required: true
  - type: dropdown
    id: office
    attributes:
      label: Office Version
      options:
        - office 2016 retail
        - office 2019 retail
        - office 2021
        - microsoft 365
        - others
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Feature request
      description: Describe in detail the features you envision or improvements to existing features
    validations:
      required: true
