export const localStorageKey = {
  // common
  chatMode: 'chatMode',
  api: 'api',
  localLanguage: 'localLanguage',
  replyLanguage: 'replyLanguage',
  insertType: 'insertType',
  useWordFormatting: 'useWordFormatting',
  useSelectedText: 'useSelectedText',
  agentMaxIterations: 'agentMaxIterations',
  enableMarkdown: 'enableMarkdown',
  horizontalToolCalls: 'horizontalToolCalls',
  attachmentCharLimit: 'attachmentCharLimit',
  llmTimeout: 'llmTimeout',
  historyDbPath: 'historyDbPath',
  tavilyApiKey: 'tavilyApiKey',
  threadId: 'threadId',
  // openai api
  apiKey: 'apiKey',
  model: 'model',
  customModel: 'customModel',
  customModels: 'customModels',
  temperature: 'temperature',
  maxContextTokens: 'maxContextTokens',
  basePath: 'basePath',
  // azure api
  azureAPIKey: 'azureAPIKey',
  azureAPIEndpoint: 'azureAPIEndpoint',
  azureDeploymentName: 'azureDeploymentName',
  azureMaxContextTokens: 'azureMaxContextTokens',
  azureTemperature: 'azureTemperature',
  azureAPIVersion: 'azureAPIVersion',
  azureModel: 'azureModel',
  azureCustomModels: 'azureCustomModels',
  // gemini api
  geminiAPIKey: 'geminiAPIKey',
  geminiMaxContextTokens: 'geminiMaxContextTokens',
  geminiTemperature: 'geminiTemperature',
  geminiModel: 'geminiModel',
  geminiCustomModel: 'geminiCustomModel',
  geminiCustomModels: 'geminiCustomModels',
  // ollama api
  ollamaEndpoint: 'ollamaEndpoint',
  ollamaModel: 'ollamaModel',
  ollamaTemperature: 'ollamaTemperature',
  ollamaCustomModel: 'ollamaCustomModel',
  ollamaCustomModels: 'ollamaCustomModels',
  ollamaMaxContextTokens: 'ollamaMaxContextTokens',
  // groq api
  groqAPIKey: 'groqAPIKey',
  groqTemperature: 'groqTemperature',
  groqMaxContextTokens: 'groqMaxContextTokens',
  groqModel: 'groqModel',
  groqCustomModel: 'groqCustomModel',
  groqCustomModels: 'groqCustomModels',
  // lmstudio api
  lmstudioEndpoint: 'lmstudioEndpoint',
  lmstudioFilterThinking: 'lmstudioFilterThinking',
  lmstudioMaxContextTokens: 'lmstudioMaxContextTokens',
  lmstudioTemperature: 'lmstudioTemperature',
  lmstudioModel: 'lmstudioModel',
  lmstudioCustomModel: 'lmstudioCustomModel',
  lmstudioCustomModels: 'lmstudioCustomModels',
  // anthropic api
  anthropicAPIKey: 'anthropicAPIKey',
  anthropicModel: 'anthropicModel',
  anthropicCustomModel: 'anthropicCustomModel',
  anthropicCustomModels: 'anthropicCustomModels',
  anthropicTemperature: 'anthropicTemperature',
  anthropicMaxContextTokens: 'anthropicMaxContextTokens',
  // togetherai api
  togetheraiAPIKey: 'togetheraiAPIKey',
  togetheraiTemperature: 'togetheraiTemperature',
  togetheraiMaxContextTokens: 'togetheraiMaxContextTokens',
  togetheraiModel: 'togetheraiModel',
  togetheraiCustomModel: 'togetheraiCustomModel',
  togetheraiCustomModels: 'togetheraiCustomModels',
  // mcp
  enabledMcpTools: 'enabledMcpTools',
  // proxy
  enableProxy: 'enableProxy',
  proxy: 'proxy',
  defaultSystemPrompt: 'defaultSystemPrompt',
  defaultPrompt: 'defaultPrompt',
} as const
